services:
  api:
    image: inspiron-agent:latest
    build: .
    pull_policy: never
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads

  ui:
    image: inspiron-agent:latest
    pull_policy: never
    command: streamlit run app_streamlit.py --server.address=0.0.0.0 --server.port=8501
    ports:
      - "8501:8501"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - api
